site_name: Auto Chat Maker ドキュメント
site_description: Auto Chat Makerプロジェクトの開発ドキュメント
site_author: 開発チーム

theme:
  name: material
  language: ja
  custom_dir: docs/stylesheets
  extra_css:
    - extra.css

plugins:
  - search
  - mermaid2

# 静的ファイルを含める
extra_files:
  - admin/

nav:
  - ホーム: index.md
  - 要件定義:
      - 概要: requirements/README.md
      - ビジネス要件: requirements/business-requirements.md
      - 機能要件: requirements/functional-requirements.md
      - 非機能要件: requirements/non-functional-requirements.md
      - 技術要件: requirements/technical-requirements.md
      - 制約事項: requirements/constraints.md
      - ユースケース:
          - 概要: requirements/use-cases.md
          - 詳細仕様: requirements/use-case-specifications.md
          - ユースケース図: requirements/use-case-diagram.md
          - シーケンス図: requirements/sequence-diagram.md
  - 設計書:
      - 概要: design/README.md
      - システムアーキテクチャ: design/system-architecture.md
      - 技術設計: design/technical-design.md
      - データベース設計:
          - スキーマ設計: design/database-schema.md
          - ER図: design/er-diagram.md
      - フェーズ別設計:
          - フェーズ1 MCP統合設計: design/phase1-5-mcp-integration-design.md
          - フェーズ1 クラス設計: design/phase1-class-design.md
          - フェーズ2 コア機能設計: design/phase2-core-functionality-design.md
          - フェーズ3 データ・UI設計: design/phase3-data-ui-design.md
      - テストケース:
          - 概要: design/test-cases/README.md
          - テストケース概要: design/test-cases/test-case-overview.md
          - テストケース要約: design/test-cases/test-case-summary.md
          - 単体テストケース: design/test-cases/unit-test-cases.md
          - 統合テストケース: design/test-cases/integration-test-cases.md
          - テスト実装計画: design/test-cases/test-implementation-plan.md
          - テストカバレッジ分析: design/test-cases/test-coverage-analysis.md
      - 仕様書:
          - 技術仕様: design/technical-specification.md
          - アーキテクチャ仕様: design/architecture.md
          - Azure AD認証仕様: design/azure-ad-auth-spec.md
          - MCP統合仕様: design/mcp-integration-spec.md
          - Webhook処理仕様: design/webhook-processing-spec.md
  - 開発ルール:
      - 開発者ガイド: instructions/developer-guide.md
      - 環境設定ガイド: instructions/environment-setup.md
      - コントリビューションガイド: instructions/contributing.md
      - コード品質チェック: instructions/code-quality-check.md
      - DeCap CMSセットアップ: instructions/decap-cms-setup.md
  - スケジュール:
      - 概要: schedule/README.md
      - 開発計画: schedule/development-plan.md
      - 進捗管理: schedule/progress-management.md
      - 実装状況レポート: schedule/implementation-status-report.md
      - 実装済みファイルチェックリスト: schedule/implemented-files-checklist.md
      - フェーズ別詳細設計:
          - フェーズ1 クラス設計: design/phase1-class-design.md
          - フェーズ1.5 MCP統合設計: design/phase1-5-mcp-integration-design.md
          - フェーズ2 コア機能設計: design/phase2-core-functionality-design.md
          - フェーズ3 データ・UI設計: design/phase3-data-ui-design.md
