backend:
  name: git-gateway

media_folder: "docs/images"
public_folder: "/images"

locale: 'ja'

collections:
  - name: "test"
    label: "テスト"
    files:
      - label: "テストページ"
        name: "test"
        file: "docs/test.md"
        fields:
          - {label: "タイトル", name: "title", widget: "string"}
          - {label: "本文", name: "body", widget: "markdown"}
